aristotle-mdr/aristotle-metadata-registry

aristotle_mdr/forms/search.py, aristotle_mdr/static/aristotle_mdr/aristotle.less, aristotle_mdr/templates/aristotle_mdr/concepts/dataElement.html, aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, aristotle_mdr/templates/aristotle_mdr/helpers/downloadMenu.html, aristotle_mdr/templates/aristotle_mdr/user/userHome.html, aristotle_mdr/templates/search/search.html
=> corrected google search

aristotle_mdr/required_settings.py, aristotle_mdr/tests/main/test_admin_pages.py, aristotle_mdr/tests/settings.py, example_mdr/example_mdr/settings.py
This makes cloning and getting it running much quicker. See: https://github.com/aristotle-mdr/aristotle-metadata-registry/wiki/Developers-Guide#setting-up-a-development-environment-on-cloud9
=> Improved where aristotle was in INSTALLED_APPS

.travis.yml, README.rst, setup.py
=> code-climate-addons

aristotle_mdr/templates/aristotle_mdr/static/extensions.html
=> fixes #221

aristotle_mdr/admin.py, aristotle_mdr/models.py, aristotle_mdr/templates/aristotle_mdr/concepts/unitOfMeasure.html, aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_wrapper.html, aristotle_mdr/templates/aristotle_mdr/scripts.html, aristotle_mdr/templates/aristotle_mdr/static/measure.html, aristotle_mdr/templates/aristotle_mdr/unmanaged/measure.html, aristotle_mdr/tests/main/test_html_pages.py, aristotle_mdr/urls_aristotle.py, aristotle_mdr/views/views.py
Also upgrades version of jquery to remove XHR warning.
=> fixes autocompletes in templates

aristotle_mdr/forms/admin.py, aristotle_mdr/forms/creation_wizards.py, aristotle_mdr/models.py, aristotle_mdr/required_settings.py, aristotle_mdr/static/aristotle_mdr/aristotle.dashboard.less, aristotle_mdr/static/aristotle_mdr/aristotle.less, aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_wrapper.html, aristotle_mdr/templates/aristotle_mdr/user/userReadyForReview.html, aristotle_mdr/templates/aristotle_mdr/user/userRegistrarTools.html, aristotle_mdr/tests/main/test_html_pages.py, aristotle_mdr/views/views.py, aristotle_mdr/views/wizards.py, docs/installing/settings.rst
This needs documentation and testing before a merge.
=> Workgroup changes settings

README.rst
Fixing Sams stupid errors reported by Johan
=> Fix #231 Spelling errors in readme file

aristotle_mdr/templates/aristotle_mdr/static/all_items.html
Not sure if "registry" was the intended term to use but i am suggesting the change.
The term registry is used further down on the same page.
=> Found a mention of "repostitory"

aristotle_mdr/required_settings.py, aristotle_mdr/static/aristotle_mdr/aristotle.less, aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, aristotle_mdr/templates/aristotle_mdr/header.html, aristotle_mdr/templates/aristotle_mdr/static/accessibility.html, aristotle_mdr/templates/aristotle_mdr/user/userSideBar.html
=> Close issue 245

aristotle_mdr/admin.py, aristotle_mdr/templates/aristotle_mdr/helpers/paginated_list.html, aristotle_mdr/templates/aristotle_mdr/helpers/paginated_reversion_list.html, aristotle_mdr/templates/aristotle_mdr/helpers/paginated_workgroup_list.html, aristotle_mdr/templates/aristotle_mdr/static/home.html, aristotle_mdr/templates/aristotle_mdr/user/userSideBar.html, aristotle_mdr/templates/aristotle_mdr/user/userWorkgroupArchives.html, aristotle_mdr/templates/aristotle_mdr/user/userWorkgroups.html, aristotle_mdr/templatetags/aristotle_tags.py, aristotle_mdr/tests/main/test_user_pages.py, aristotle_mdr/views/user_pages.py, aristotle_mdr/views/utils.py
=> Added sorting for workgroups, fixes #251

aristotle_mdr/forms/creation_wizards.py, aristotle_mdr/templates/aristotle_mdr/actions/advanced_editor.html, aristotle_mdr/tests/main/test_html_pages.py, aristotle_mdr/tests/utils.py
Adds new feature for preventing overwriting of content.
=> Check last save

aristotle_mdr/tests/apps/bulk_actions_test/actions.py, aristotle_mdr/tests/apps/extension_test/admin.py, aristotle_mdr/tests/apps/extension_test/apps.py, aristotle_mdr/tests/apps/extension_test/extension_urls.py, aristotle_mdr/tests/apps/extension_test/models.py, aristotle_mdr/tests/apps/extension_test/urls.py, aristotle_mdr/tests/apps/extension_test/views.py, aristotle_mdr/tests/apps/text_download_test/apps.py, aristotle_mdr/tests/apps/text_download_test/downloader.py, aristotle_mdr/tests/apps/text_download_test/models.py, aristotle_mdr/tests/extensions/test_bulk_actions.py, aristotle_mdr/tests/extensions/test_downloaders.py, aristotle_mdr/tests/extensions/test_extension_api.py, aristotle_mdr/tests/main/test_bulk_actions.py, aristotle_mdr/tests/main/test_caching.py, aristotle_mdr/tests/main/test_comparator.py, aristotle_mdr/tests/main/test_supersedes.py, aristotle_mdr/tests/main/test_templatetags.py, aristotle_mdr/tests/main/test_user_pages.py, aristotle_mdr/tests/querysets/test_querysets.py, aristotle_mdr/tests/settings.py, aristotle_mdr/tests/utils.py
I got through this much before I saw your comment about leaving the test suite.
=> Style: fix ~1/3 of the PEP8 warnings in tests

aristotle_mdr/locale/fr/LC_MESSAGES/django.po
I will need more context for the following:
#: templates/aristotle_mdr/concepts/managedContent.html:33
msgid "Admin editor"
--> is it "editor for the Admin" or "tool for editing the admins"?
#: templates/aristotle_mdr/user/userSideBar.html:86
msgid "Review list"
--> (Verb) review a list, or list of reviews?
#: utils.py:29
msgid " (clone)"
--> verb or noun?
#: utils.py:61
#, python-format
msgid "Added %(name)s \"%(object)s\"."
--> example?
#: utils.py:65
#, python-format
msgid "Changed %(list)s for %(name)s \"%(object)s\"."
--> example?
#: utils.py:70
#, python-format
msgid "Deleted %(name)s \"%(object)s\"."
--> example?
=> French translation

aristotle_mdr/contrib/whoosh_backend.py, aristotle_mdr/forms/search.py, aristotle_mdr/required_settings.py, aristotle_mdr/search_indexes.py, aristotle_mdr/static/aristotle_mdr/aristotle_search.less, aristotle_mdr/templates/aristotle_mdr/helpers/itemLink.html, aristotle_mdr/templates/search/search.html, aristotle_mdr/templatetags/aristotle_search_tags.py, aristotle_mdr/templatetags/aristotle_tags.py, aristotle_mdr/tests/main/test_search.py, aristotle_mdr/tests/settings.py, aristotle_mdr/views/views.py
=> Facet search

README.rst
"Fix" some links in the wiki to point to the Aristotle-MDR org.
=> Change README to link to aristotle-mdr org

aristotle_mdr/tests/main/test_wizards.py, aristotle_mdr/views/wizards.py
=> better checks for create pages for non-allowed users & tests

aristotle_mdr/models.py, aristotle_mdr/static/aristotle_mdr/aristotle_search.less, aristotle_mdr/templates/search/search.html, aristotle_mdr/templates/search/searchItem.html, aristotle_mdr/tests/main/test_search.py
=> Minor fixes

aristotle_mdr/contrib/help/templates/aristotle_mdr_help/base.html, aristotle_mdr/models.py, aristotle_mdr/templates/aristotle_mdr/actions/changeStatus.html, aristotle_mdr/templates/aristotle_mdr/actions/check_states.html, aristotle_mdr/templates/aristotle_mdr/base.html, aristotle_mdr/templates/aristotle_mdr/concepts/actionbar.html, aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, aristotle_mdr/templates/aristotle_mdr/header.html, aristotle_mdr/templates/aristotle_mdr/manifest.json, aristotle_mdr/templatetags/aristotle_tags.py, aristotle_mdr/tests/main/test_html_pages.py, aristotle_mdr/urls/aristotle.py, aristotle_mdr/views/actions.py
=> Check states page to close issue 254

aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/list.html, aristotle_mdr/contrib/help/fixtures/aristotle_help/downloading_content.yaml, aristotle_mdr/downloader.py, aristotle_mdr/forms/creation_wizards.py, aristotle_mdr/models.py, aristotle_mdr/templates/aristotle_mdr/downloads/csv-vd/valuedomain.html, aristotle_mdr/templates/aristotle_mdr/helpers/downloadMenu.html, aristotle_mdr/templatetags/aristotle_tags.py, aristotle_mdr/tests/apps/text_download_test/downloader.py, aristotle_mdr/utils/__init__.py, aristotle_mdr/utils/downloads.py, aristotle_mdr/views/downloads.py, aristotle_mdr/views/views.py, docs/extensions/downloads.rst
=> better download api

aristotle_mdr/templates/aristotle_mdr/static/home.html, aristotle_mdr/tests/main/test_html_pages.py, aristotle_mdr/urls/aristotle.py, aristotle_mdr/views/views.py
=> change allRegistrationAuthorities name to underscore case

aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/apps_list.html, aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/model_list.html, aristotle_mdr/contrib/browse/tests/test_browse.py
=> Hide matadata items if they are zero

python/aristotle-metadata-registry/CHANGELOG.md, python/aristotle-metadata-registry/aristotle_mdr/fields.py, python/aristotle-metadata-registry/aristotle_mdr/forms/actions.py, python/aristotle-metadata-registry/aristotle_mdr/forms/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/static/aristotle_mdr/aristotle.js, python/aristotle-metadata-registry/aristotle_mdr/static/aristotle_mdr/aristotle.status_change.js, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/bulk_actions/change_status.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/bulk_actions/request_review.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/changeStatus.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/request_review.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/review_state_changes.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/changestatus.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/wizard_form.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/user_request_accept.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/widgets/table_checkbox_option.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/widgets/table_checkbox_select.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/util_tags.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_reviews.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/utils/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/actions.py, python/aristotle-metadata-registry/aristotle_mdr/views/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py, python/aristotle-metadata-registry/aristotle_mdr/widgets/widgets.py
Ability to review changes when changing status from single ite, from bulk action, on review accept
Bug fix for help page search items is also in here
=> Added wizard views to review state changes

python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/templates/aristotle_mdr/generic/actions/alter_one_to_many_formstage.html, python/aristotle-metadata-registry/aristotle_mdr/forms/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/static/aristotle_mdr/aristotle_search.less, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/edit_value_domain_values.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/static/home.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userHome.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_utils.py, python/aristotle-metadata-registry/aristotle_mdr/utils/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
This Fixes the following
- Error text for favorite bulk action showing when it shouldn't
- Formstage sometimes being visible before css has loaded
- Broken help link on homepage
- Search result badge widths different depending on results
- Dashboard queries
- Logout from dashboard closes #773
=> Various small fixes

python/aristotle-metadata-registry/aristotle_mdr/static/aristotle_mdr/aristotle.js, python/aristotle-metadata-registry/aristotle_mdr/static/aristotle_mdr/aristotle.notify.js, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/scripts.html, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/views/__init__.py, python/aristotle-metadata-registry/aristotle_mdr/views/notify.py
- Only load when user clicks header icon
=> Update to notifications loading

CHANGELOG.md, setup.py
=> 2.1.2 Prep

python/aristotle-mdr-api/aristotle_mdr_api/v2/views/concepts.py, python/aristotle-mdr-api/aristotle_mdr_api/v3/views/concepts.py
=> Fix api metadata list

python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/models.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/tests.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/urls.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/views.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/slots/forms.py, python/aristotle-metadata-registry/aristotle_mdr/forms/search.py, python/aristotle-metadata-registry/aristotle_mdr/search_indexes.py, python/aristotle-metadata-registry/aristotle_mdr/signals.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_search.py
- Identifier and Namespace token search
- Explicit list of allowed tokens
- Reindexing on identifier save
- Updated identifier redirect view
- Unit tests
closes #870 
Sanity checks:
=> Identifier Search

python/aristotle-metadata-registry/aristotle_mdr/contrib/user_management/templates/aristotle_mdr/users_management/users/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/user_management/views.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_workgroup_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userSideBar.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userWorkgroups.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/workgroups.py
This closes #869 and closes #871 
Sanity checks:
=> Efficiency improvements for listing

CHANGELOG.md, Pipfile.lock, python/aristotle-metadata-registry/aristotle_mdr/contrib/user_management/models.py, python/aristotle-metadata-registry/setup.py, setup.py
Remove pin to alpha version
Sanity checks:
=> Update django-improved-user dependancy

Pipfile.lock, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/actions/edit_inclusion_order.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-metadata-registry/setup.py
=> Fix dataset display and reordering

.travis.yml, Pipfile.lock, docker/sh/entrypoint/web.sh, docs/requirements.txt, python/aristotle-bg-workers/aristotle_bg_workers/tests.py, python/aristotle-metadata-registry/setup.py, scripts/check_path.sh, scripts/tox_if.sh, tox.ini
- Use test utils
- Add workers module to tox/travis
- Add --reload to gunicorn args to automatically restart workers
Sanity checks:
=> Background worker tests

python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/base.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/static/home.html, python/aristotle-metadata-registry/aristotle_mdr/urls/base.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Redirect to home with message on logout

Pipfile, Pipfile.lock, python/aristotle-metadata-registry/setup.py
=> Update django version to 1.11.16

python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_discussions.py
=> Fix issue with discussions notifications

python/aristotle-metadata-registry/aristotle_mdr/admin.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py
=> Fix creation of unneccesary versions on linked items

python/aristotle-metadata-registry/aristotle_mdr/static/aristotle_mdr/aristotle.moveable.js
=> Add includes polyfill in movebale.js for now

python/aristotle-metadata-registry/aristotle_mdr/contrib/favourites/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Fix public item page display

python/aristotle-metadata-registry/aristotle_mdr/contrib/favourites/tests.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/static/aristotle_mdr/ajaxforms.js, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/sandbox.html
=> Fix to ajaxforms javascript

python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
=> Fix to slots saving

Pipfile, Pipfile.lock, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/schema/schema.json, python/aristotle-metadata-registry/aristotle_mdr/schema/setup.yaml, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/validate.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_validation.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/utils/downloads.py, python/aristotle-metadata-registry/aristotle_mdr/validators.py, python/aristotle-metadata-registry/aristotle_mdr/views/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/views/downloads.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py, python/aristotle-metadata-registry/setup.py, setup.cfg
=> Prototype for metadata validation

python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Add app check to item page

assets/test/apiRequest_test.js, scripts/buildandcopy.sh
=> Extra issues test, Fix copy script

scripts/buildandcopy.sh
=> Add install to build script

scripts/buildandcopy.sh
=> Fix script path

assets/src/lib/notify.js
=> Notifications fix for IE

python/aristotle-metadata-registry/aristotle_mdr/messages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_notifications.py
=> fix notifications, add test

.travis.yml, Pipfile.lock
=> Update travis deploy

docker/settings.py, python/aristotle-metadata-registry/aristotle_mdr/storage.py, scripts/buildandcopy.sh
=> Added no logging env var

scripts/buildandcopy.sh
=> Add disable env var

assets/package-lock.json, assets/src/lib/changeStatus.js, assets/src/lib/dal_simple_init.js, assets/src/lib/init.js, assets/src/lib/itemPage.js, assets/src/lib/moveable.js, assets/src/pages/dashboard.js, assets/src/styles/aristotle.autocomplete.css, docker/settings.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/aristotle_mdr.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/async_signals/concept_changes.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/autocomplete/templates/aristotle_mdr/actions/autocompleteUser.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/templates/aristotle_mdr/generic/actions/alter_one_to_many_formset.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/publishing/views.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/storage.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/contentInfoBase.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, scripts/buildandcopy.sh, setup.py
=> Script fix + links fix

setup.py
=> Remove the dash

.travis.yml
=> Isolate the pypi deployment

python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/templates/aristotle_mdr/generic/actions/alter_one_to_many_formset.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/bulk_actions/lots_of_things.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/user_request_cancel.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/user_request_reject.html, python/aristotle-metadata-registry/aristotle_mdr/tests/apps/bulk_actions_test/templates/confirm_delete.html
=> Remove form media

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/fancy_form.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/sandbox.html, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
Changed button wording, alert message, and implemented a counter for the number of email addresses the user is sharing content with.
Sanity checks:
=> Improved user experience for the Share Link in the Sandbox page.

assets/src/lib/multifield.js, python/aristotle-bg-workers/aristotle_bg_workers/tasks.py, python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/fancy_form.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/sandbox.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/widgets/multi_input.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
Implemented notification email option for Sandbox Sharelink popup. Implemented Tests. Improved existing validation and created JavaScript email validation.
=> Implemented notification email option in Sandbox Sharelink popup

python/aristotle-dataset-extensions/aristotle_dse/models.py, python/aristotle-dataset-extensions/aristotle_dse/tests/test_dse.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_actions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
Cloning now copies components across for value domains and data set specifications
Sanity checks:
=> Cloning components

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userRoles.html, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Implemented corrected ordering to roles according to GitHub issue #1033

Pipfile, Pipfile.lock, python/aristotle-metadata-registry/setup.py
https://docs.djangoproject.com/en/2.1/releases/1.11.18/
Sanity checks:
=> Update django version

python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/views.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
Fixes empty 404 pages on some views
Sanity checks:
=> Switch to Http404 exception

python/aristotle-metadata-registry/aristotle_mdr/contrib/user_management/models.py
=> Add properties to user model for compatibility with django apps

python/aristotle-dataset-extensions/aristotle_dse/tests/urls.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/changestatus.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/util_tags.py, python/aristotle-metadata-registry/aristotle_mdr/tests/settings/settings.py
=> Isotime template fix

Pipfile.lock, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/forms.py, python/aristotle-metadata-registry/aristotle_mdr/forms/fields.py, python/aristotle-metadata-registry/aristotle_mdr/managers.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/valueDomainRepresentation.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/settings/settings.py, python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py, python/aristotle-metadata-registry/setup.py
=> Optimize bulk component changes

python/aristotle-metadata-registry/aristotle_mdr/storage.py, scripts/buildandcopy.sh
=> Simplifyed deployment

assets/package-lock.json, assets/src/lib/notify.js, python/aristotle-metadata-registry/aristotle_mdr/contrib/async_signals/action_signals.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/async_signals/concept_changes.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/models.py, python/aristotle-metadata-registry/aristotle_mdr/messages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_notifications.py
Improved the notifications messages. If there is no Workgroup available the message doesn't include the Workgroup.
Sanity checks:
=> Improved the notifications messages.

python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/templates/aristotle_mdr/issues/display.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/templates/aristotle_mdr/issues/sublist.html
=> Issues ui 1087

python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/views.py
=> make stewards page faster with more content

assets/package-lock.json, scripts/buildandcopy.sh, setup.py
=> Changes for rc5 deploy

python/aristotle-metadata-registry/aristotle_mdr/contrib/aristotle_backwards/templates/aristotle_mdr_backwards/concepts/classificationscheme.html
=> add page for CS's

python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/stewards/managed_item/edit.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py, python/aristotle-metadata-registry/aristotle_mdr/forms/discussions.py, python/aristotle-metadata-registry/aristotle_mdr/forms/utils.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/edit.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/new.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/manageditems/fallback.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/manageditems/helpers/actionbar.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/manageditems/infoBase.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/manageditems/titles/display_title.html, python/aristotle-metadata-registry/aristotle_mdr/views/views.py, python/comet-indicator-registry/comet/templates/comet/outcomearea.html, python/comet-indicator-registry/comet/urls.py
=> Fix managed

assets/package-lock.json, assets/src/styles/aristotle.compare.less, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/compare/compare_items.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/concept_history_compare.html, python/aristotle-metadata-registry/aristotle_mdr/templates/reversion-compare/action_list_partial.html, python/aristotle-metadata-registry/aristotle_mdr/templates/reversion-compare/compare_partial.html
=> Improved the diff items colours.

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/tests.py, python/aristotle-metadata-registry/aristotle_mdr/forms/search.py, python/aristotle-metadata-registry/aristotle_mdr/search_indexes.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/static/home.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/indexes/aristotle_mdr/managedobject_text.txt, python/aristotle-metadata-registry/aristotle_mdr/templates/search/search.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_search.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
- Search text changes
- Add uuid to search index
- Add uuid: search keyword
- Search item name boosting
- Restrict similar items in advanced wizards
=> Various enhancements

python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/stewards/managed_item/edit.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/templates/aristotle_mdr/validation/edit.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/manageditems/helpers/actionbar.html
=> More minor fixes

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Fixed error and created tests so it doesn't happen again.

assets/src/pages/wizard.js, assets/src/settings.json, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
- Hide advanced wizard components tab
- Add wizard prompt for navigating away
=> Small enhancements

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/backends.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/templates/groups/group/create.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/create.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/stewards/base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/user/organisations/list_all.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/groups/base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py, python/aristotle-metadata-registry/aristotle_mdr/models.py
=> Fixed redirection of Stewardship creation button.

python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/valueDomain.html, python/comet-indicator-registry/comet/templates/comet/indicatorset.html
=> minor template fixes

assets/src/lib/init.js, assets/src/lib/suggest.js, assets/src/lib/utils.js, assets/src/pages/wizard.js, assets/test/utils_test.js, assets/webpack.common.js, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/aristotle_backwards/tests.py, python/aristotle-metadata-registry/aristotle_mdr/forms/creation_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/widgets/widgets.py
- Name suggest button for DEC & DE
- Occurrances spelling fix
- Make webpack fail on bad imports
- Fix IE11 img-responsive
- Show orgnisation fields when no references
=> Name suggest button, plus additional enhancements

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/custom_fields_display.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/delete.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/multiedit.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/util_tags.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_templatetags.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Custom fields are hidden if the string content is empty. Also implemented a table default styling.

Pipfile.lock, assets/package-lock.json, python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/views.py
=> Fixed problem with General Graph for Datasets.

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/runners.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/tests.py
=> Fixed yaml.safe_load() when the default parameter is an empty string.

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/details.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/collections.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/schema/schema.json, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userSideBar.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_permissions.py, python/aristotle-metadata-registry/aristotle_mdr/views/utils.py
=> Collections

python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/runners.py
=> Fixed problem with last PR.

python/aristotle-glossary/aristotle_glossary/admin.py, python/aristotle-glossary/aristotle_glossary/models.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/steward_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/registration_authority/steward_list.html
=> fix add button on stewards

python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/tests.py, python/aristotle-metadata-registry/aristotle_mdr/perms.py, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
=> Sentry fixes

assets/src/lib/notify.js, python/aristotle-metadata-registry/aristotle_mdr/context_processors.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/base.html, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userInbox.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userSideBar.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Notifications pagination

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/helpers/paginated_review_list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/my_review_list.html
=> Implemented create review button in reviews page

python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/runners.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/schema/schema.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/validators/tests.py
=> Finished solving this issue.

Pipfile.lock, python/aristotle-metadata-registry/aristotle_mdr/utils/cached_querysets.py, python/aristotle-metadata-registry/aristotle_mdr/views/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Fixed sentry EOFError caused by Django caching bulk actions.

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/tests.py
=> Solved supersede form sentry issue.

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/tests.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templatetags/util_tags.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_templatetags.py
=> Uploaded profile pictures now can be bigger than 2.5 Mb.

python/aristotle-metadata-registry/aristotle_mdr/downloader.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_downloads.py
=> Downloads fixes

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/registration_authority/remove_member.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/workgroups/remove_member.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_registrationauthority.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py
=> Users are not removed from wg or ra fix

assets/package-lock.json, assets/src/pages/datasetSpecification.js, assets/src/styles/aristotle.less, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html
=> Implemented 'show all Data Elements' for Dataset Specification Clusters.

python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/custom_fields_display.html
=> Fixed template

docs/api/graphql.rst, python/aristotle-mdr-api/aristotle_mdr_api/token_auth/mixins.py, python/aristotle-mdr-api/aristotle_mdr_api/token_auth/tests.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/aristotle_dse.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/aristotle_mdr.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/schema.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/user.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/templates/aristotle_mdr_graphql/explorer.html, python/aristotle-mdr-graphql/aristotle_mdr_graphql/tests/tests.py
=> Fixed GraphQL documentation

python/aristotle-metadata-registry/aristotle_mdr/search_indexes.py, python/aristotle-metadata-registry/aristotle_mdr/signals.py, python/aristotle-metadata-registry/aristotle_mdr/templates/search/indexes/aristotle_mdr/discussionpost_text.txt, python/aristotle-metadata-registry/aristotle_mdr/templates/search/indexes/aristotle_mdr/stewards/collection_text.txt, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Search pull request fixes

python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/comet.py, python/comet-indicator-registry/comet/models.py
=> Implemented IndicatorSets and QualityStatements for GraphQL endpoint.

assets/package-lock.json, assets/package.json, assets/src/lib/ckeditor_plugins.js, assets/src/lib/ckeditor_simple_init.js, python/aristotle-glossary/aristotle_glossary/settings.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py
right, center) to rich text editor. Removed superfluous requests.
Sanity checks:
=> Text alignment for the HTML Editor 

assets/package.json, assets/src/custom/assets/init.js, assets/src/pages/custom.js, assets/webpack.common.js, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/footer.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html
=> Better custom templating

python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/aristotle_mdr.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/models.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/details.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/helpers/actionbar.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/collections.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py
=> add collections to graphql

Pipfile, Pipfile.lock
=> Updated urllib3

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/changestatus.html
Fixes issues: # 107
Sanity checks:
=> Removed (optional) tag from change status

python/comet-indicator-registry/comet/models.py
=> remove field

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html
=> fix template

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/helpers/accept_review_info.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/helpers/paginated_review_list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/details.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/inline/valueDomainRepresentation.html
=> minor review fixes

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/workgroups/change_role.html
=> fix MTP#78

python/aristotle-metadata-registry/aristotle_mdr/urls/__init__.py, python/aristotle-metadata-registry/aristotle_mdr/views/debug.py
=> pdf debugger

python/aristotle-bg-workers/aristotle_bg_workers/tasks.py, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/backends.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Hover text for length heading on table

python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/backends.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/tests/test_groups.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/urls.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_downloads.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Code fixes

python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html
=> minor html fix

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/inlineDetails.html
=> Improved template.

python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/helpers/actionbar.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/helpers/paginated_organisation_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_registration_authority_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_workgroup_list.html
=> Added collections in infobox

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/objectClass.html, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> faster oc page load

python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py, python/aristotle-metadata-registry/aristotle_mdr/managers.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/organization/registration_authority/data_dictionary.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_registrationauthority.py, python/aristotle-metadata-registry/aristotle_mdr/views/registrationauthority.py
=> Data dictionary fix

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/organization/registration_authority/data_dictionary.html, python/aristotle-metadata-registry/aristotle_mdr/views/registrationauthority.py
=> minor qs fix. add pagination

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/organization/registration_authority/base.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userAdminTools.html
=> links to pages, uncomment dd tab

assets/src/lib/formset.js, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/slots/templates/aristotle_mdr/slots/slots_editor_tab.html, python/aristotle-metadata-registry/aristotle_mdr/forms/creation_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/advanced_editor.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
=> Add a record relation to link concept to Organisation Record

assets/src/lib/formset.js, assets/src/lib/moveable.js, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py, python/comet-indicator-registry/comet/models.py
=> fix managed item counts, fixed MRP#162

python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/custom_fields_display.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html
=> Removed extra space

python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/custom_fields_display.html
=> Improved wrapping of custom fields

python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/custom_fields_display.html
=> Occurrence spelling fix

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
=> Proposed supersedes in infobox

python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/organization/registration_authority/data_dictionary.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_registrationauthority.py, python/aristotle-metadata-registry/aristotle_mdr/utils/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/registrationauthority.py, python/aristotle-metadata-registry/aristotle_mdr/widgets/bootstrap.py
=> Filtering on concept type in data dictionary

Pipfile.lock, assets/package-lock.json, python/aristotle-mdr-api/setup.py, python/aristotle-metadata-registry/aristotle_mdr/models.py
=> Added blank=True to _type field in _concept.

assets/package-lock.json, assets/src/pages/reviews/review_impacts.js
=> Fixed promote button under impact not working

assets/package-lock.json, assets/src/pages/wizard.js, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/add_link_wizard_2_select_role.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/views.py
=> Fix add relation 404ing

assets/package-lock.json, assets/src/pages/wizard.js, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/add_link_wizard_2_select_role.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/tests/test_links.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/views.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_supersedes.py, python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/actions.py
=> Fix for relation role saving failing

python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/forms/collections.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/details.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/tests/test_collections.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/collections.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/utils.py
=> Aggregate count of collections

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/workgroups/members.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/workgroup.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_workgroups.py
=> Permissions checking around adding a user to a workgroup

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/bulk_actions/bulk_download.html
=> Removed floating colon in download view

python/aristotle-metadata-registry/aristotle_mdr/forms/search.py, python/aristotle-metadata-registry/aristotle_mdr/search_indexes.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_search.py
=> Filtering on first created, and last created

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/custom_fields_display.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/component/custom_fields_display.html
=> Added indentation to HTML custom fields

python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/forms/collections.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/models.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/add.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/details.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/edit.html
=> fix MRP#192

python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/templates/aristotle_mdr/generic/actions/confirm_delete.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_discussions.py, python/aristotle-metadata-registry/aristotle_mdr/views/discussions.py, python/aristotle-metadata-registry/aristotle_mdr/views/utils.py
=> Confirm delete view for discussion posts

python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/backends.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/base.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/templates/groups/group/members/add.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/templates/groups/group/members/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/templates/groups/group/members/remove.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/templates/groups/group/members/update.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/organization/registration_authority/data_dictionary.html
=> Steward page improvements

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/browse/dataElements.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/wizard_search_result_item.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/inlineDetails.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_registration_authority_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/organization/all_registration_authorities.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/searchItem.html, python/aristotle-metadata-registry/aristotle_mdr/utils/utils.py
=> Fixed non-breaking space in Registration Authorities page.

assets/package-lock.json, python/aristotle-dataset-extensions/aristotle_dse/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_reversion_list.html, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
=> Added __str__ methods for DSSDEInclusion and DSSClusterInclusion

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/dataType.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/unitOfMeasure.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
=> minor template fix, allow safe zws

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/templates/aristotle_mdr/custom_fields/custom_fields_display.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/itemLink.html
=> switch to dl's

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py, python/aristotle-metadata-registry/aristotle_mdr/messages.py
=> Capitalised words in Notification Permissions form.

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_registration_authority_list.html
=> improve page

python/aristotle-metadata-registry/aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/apps_list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/model_list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/browse/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/create_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userAdminStats.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userAdminTools.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/util_tags.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Better browse consistency

python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/utils/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Enhancements

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/tests.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/static/home.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
=> fix MRP#200, fix #1317

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userAdminStats.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userAdminTools.html
=> minor stats fix

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/aristotle_pdf/pdf_static/css/pdf.css, python/aristotle-metadata-registry/aristotle_mdr/downloader.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/component/custom_fields_display.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/component/statuses.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/helpers/inlineDetails.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/inline/dataelement.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/inline/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/managedContent.html
=> update download templates

python/aristotle-metadata-registry/aristotle_mdr/contrib/serializers/concept_serializer.py, python/aristotle-metadata-registry/aristotle_mdr/forms/creation_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_permissions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py, python/aristotle-metadata-registry/aristotle_mdr/utils/model_utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
=> [WIP]  Reversion overhaul

python/comet-indicator-registry/comet/templates/comet/framework.html
=> Finished this functionality. Framework Dimensions are only visible in  the template if they exist.

python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Fixed type for reversion-overhaul

python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/tests.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Type fixes

python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Spelling fix

python/aristotle-dataset-extensions/aristotle_dse/tests/test_dse.py
=> Skipping outdated test

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/tools/related.html
=> fix help for related

assets/src/lib/init.js, assets/src/pages/search.js, assets/src/styles/aristotle.less, assets/src/styles/aristotle_search.less, python/aristotle-dataset-extensions/aristotle_dse/admin.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/search_indexes.py, python/aristotle-metadata-registry/aristotle_mdr/forms/search.py, python/aristotle-metadata-registry/aristotle_mdr/register.py, python/aristotle-metadata-registry/aristotle_mdr/search_indexes.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/tools/related.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/forms/widgets/search_radio.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/search.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/search_bar.html, python/aristotle-metadata-registry/aristotle_mdr/views/search.py, python/aristotle-metadata-registry/aristotle_mdr/widgets/bootstrap.py
=> Search cats

python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Fixed bug where not all DSSDEInclusions were displayed

python/aristotle-dataset-extensions/aristotle_dse/models.py, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataset.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/downloads/html/datasetspecification.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/downloads/html/helpers/inclusion_head.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/downloads/html/helpers/inclusion_row.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/downloads/html/helpers/inclusions.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/helpers/dataelementinclusion_table_head.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/helpers/dataelementinclusion_table_row.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/templates/aristotle_mdr/generic/actions/alter_one_to_many_formstage_list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/templates/aristotle_mdr/generic/actions/alter_one_to_many_formstage_table.html, python/comet-indicator-registry/comet/templates/comet/downloads/html/indicator.html
=> Inclusion rename fix

python/aristotle-mdr-api/aristotle_mdr_api/v4/custom_fields/serializers.py
=> Added help_text_long field to the API.

python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/field_help.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html
=> Remove help

python/aristotle-bg-workers/aristotle_bg_workers/tasks.py, python/aristotle-bg-workers/aristotle_bg_workers/views.py, python/aristotle-metadata-registry/aristotle_mdr/management/commands/recache_registration_authority_item_visibility.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/registration_authority/edit_states.html
=> update ra state change, fix MRP#215

python/aristotle-metadata-registry/aristotle_mdr/constants.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/managers.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/tests.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/slots/manager.py, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
=> allow superuser only CFs

python/aristotle-metadata-registry/aristotle_mdr/views/registrationauthority.py
=> Fixed data dictionary 500ing when pagination clicked

python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Refactored sending of Sandbox notifications

assets/src/lib/formset.js, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/advanced_editor.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html
=> Fixed reference documents add form button adding to organisation records

Pipfile.lock, assets/package-lock.json
=> Updated Django

python/aristotle-metadata-registry/aristotle_mdr/contrib/serializers/concept_serializer.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/compare/compare_items.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/compare/compare_table.html, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Toolbox comparison fix

python/aristotle-metadata-registry/aristotle_mdr/forms/search.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html
=> search aristotle id

python/aristotle-dataset-extensions/aristotle_dse/tests/test_dse.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/tests/test_links.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_2_results.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
=> Organisation records can be edited during concept creation

python/aristotle-bg-workers/aristotle_bg_workers/views.py
=> Fix for account/tasks/history 500ing

python/aristotle-metadata-registry/aristotle_mdr/views/editors.py, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
=> Fixed saving from clone item view not serialising correctly

python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py
=> Fixed UUID regex

python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Version comparison fixes

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_1_search.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_2_results.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_wrapper.html, python/aristotle-metadata-registry/aristotle_mdr/views/actions.py, python/comet-indicator-registry/comet/templates/comet/indicator.html
=> Next button of wizard fix

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/views/actions.py, python/comet-indicator-registry/comet/templates/comet/indicator.html
=> Fixed issue with template fields appearing blank in Indicators

python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_workgroup_list.html
=> Permission checking around viewing workgroups 

python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/backends.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/templates/groups/group/settings.html
=> Fixed display of definition in Steward's settings page

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/compare/compare_items.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/styled_difference.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
=> Fixed display of non breaking spaces for text only version comparison

assets/src/components/download.vue, python/aristotle-dataset-extensions/aristotle_dse/models.py, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/downloads/html/datasetspecification.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/downloads/html/inline/datasetspecification.html, python/aristotle-metadata-registry/aristotle_mdr/downloader.py, python/aristotle-metadata-registry/aristotle_mdr/structs.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/css/pdf.css, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/helpers/inlineDetails.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/inline/dataelement.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/inline/dataelementconcept.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/inline/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/inline/valuedomain.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/managedContent.html, setup.cfg
=> Dss downloads

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_wrapper.html
=> Fixes slots extending out of wizard

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/forms/search.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/base.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/userSideBar.html
=> minor header & menu tweaks

python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/comet.py
=> Removed FrameworkDimensions from GraphQL.

Pipfile, Pipfile.lock, assets/package-lock.json, python/aristotle-dataset-extensions/aristotle_dse/models.py, python/aristotle-glossary/aristotle_glossary/tests/tests.py, python/aristotle-mdr-api/setup.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/concept_help.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/field_help.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/views.py, python/comet-indicator-registry/comet/models.py
=> Applied ordering for Indicator Data Elements.

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/management/commands/recache_registration_authority_item_visibility.py
=> Adds flag to recache_registration_authority_item_visibility to disable reindexing search

.travis.yml, python/comet-indicator-registry/comet/managers.py, scripts/buildandcopy.sh
- Automated lib deployment
- Script cleanup
=> Automated deployment

assets/package-lock.json, assets/src/lib/concept_links.js
=> Fixed tooltip displaying html entities

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/workgroup_leave.html
=> Fixed workgroup leave request

Pipfile.lock, assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/user_management/org_backends.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_caching.py, python/aristotle-metadata-registry/aristotle_mdr/utils/cached_querysets.py, python/aristotle-metadata-registry/setup.py
=> Removes requirement to monkey patch pickles

python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/tests.py, python/aristotle-metadata-registry/aristotle_mdr/views/comparator.py, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
=> Removes refactored out help_guide function

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/user_management/models.py, python/aristotle-metadata-registry/aristotle_mdr/messages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_discussions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_search.py
=> Improved code for Notification Permissions.

python/aristotle-metadata-registry/aristotle_mdr/models.py
=> Removed outdated TODO

python/aristotle-metadata-registry/aristotle_mdr/models.py
=> Fixed ordering of permissible values

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/static/home.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/settings/templates/search/elasticsearch.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py
=> Reenable comparator tests

python/aristotle-metadata-registry/aristotle_mdr/views/registrationauthority.py, python/aristotle-metadata-registry/aristotle_mdr/views/workgroups.py
=> Refactored AddUser and AddUserView

python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py, python/aristotle-metadata-registry/aristotle_mdr/urls/aristotle.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Swapped ManagedItemsView to a CBV

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/user_management/views.py, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py, python/aristotle-metadata-registry/aristotle_mdr/views/registrationauthority.py, python/aristotle-metadata-registry/aristotle_mdr/views/utils.py
=> Removed check_permissions function

python/aristotle-dataset-extensions/aristotle_dse/tests/test_dse.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py
=> Fixes DSE tests

assets/src/components/tags/autocompleteTag.vue, assets/src/components/tags/mySimpleSuggest.vue, assets/src/components/tags/tag.vue
- Change css list-type
- Force vue-simple-suggest to not set text on input element
=> Tag input fixes

.travis.yml, scripts/tox_if.sh
=> Fixing Travis.

python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/utils.py
=> Improved imports around queryset

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py, python/aristotle-metadata-registry/aristotle_mdr/urls/base.py
=> Password reset fix

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py
=> Fixed unauthenticated users 500ing server when trying to view review

assets/package-lock.json, assets/src/pages/search.js, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/search_backends/facetted_whoosh.py, python/aristotle-metadata-registry/aristotle_mdr/forms/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/perms.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/bulk_actions/change_stewardship_organisation.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/search_bar.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_user_management.py, python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py
=> Move metadata items across Steward Organisations bulk action

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/footer.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html
=> better client customisation

python/comet-indicator-registry/comet/templates/comet/downloads/html/qualitystatement.html
=> fix QS download

python/aristotle-mdr-graphql/aristotle_mdr_graphql/types.py
=> Fixed error.

python/aristotle-bg-workers/aristotle_bg_workers/tasks.py, python/aristotle-metadata-registry/aristotle_mdr/messages.py
=> Implemented translations for notification messages.

assets/package-lock.json, python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/aristotle_mdr.py
=> Fixed GraphQL API being broken for Object Classes

python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/aristotle_mdr.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/comet.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/utils.py
=> Further GraphQL fixes

python/aristotle-mdr-graphql/aristotle_mdr_graphql/schema/comet.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py
=> Fixed broken GraphQL for Data Quality Statements

.travis.yml, assets/package-lock.json, docker/settings.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/tests/settings/settings.py, python/comet-indicator-registry/comet/tests/settings.py
=> Added unapplied migrations check to Travis

.github/pull_request_template.md, assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/workgroups/members.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/workgroup.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/workgroupItems.html, python/mallard-questionnaire-registry/mallard_qr/models.py
=> Add breadcrumbs in workgroup members page

docker/urls.py, python/aristotle-glossary/aristotle_glossary/urls.py, python/aristotle-mdr-api/aristotle_mdr_api/urls.py, python/aristotle-mdr-api/aristotle_mdr_api/v4/tags/urls.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/urls.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/backends.py, python/aristotle-metadata-registry/aristotle_mdr/urls/base.py, python/comet-indicator-registry/comet/tests/urls.py, python/comet-indicator-registry/comet/urls.py, python/mallard-questionnaire-registry/mallard_qr/models.py, python/mallard-questionnaire-registry/mallard_qr/urls.py
=> Urls improvements

CHANGELOG.md, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataset.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/distribution.html, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/valueDomainRepresentation.html, python/aristotle-metadata-registry/aristotle_mdr/utils/model_utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/workgroups.py, python/mallard-questionnaire-registry/mallard_qr/models.py
=> Minor ui fixes

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/view_history/templates/aristotle_mdr/dashboard/clear_all_recently_viewed.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/view_history/templates/aristotle_mdr/dashboard/recently_viewed.html
Issues resolved: #1111 
Sanity checks:
=> Solved hovering button issue.

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_workgroup_list.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py, python/mallard-questionnaire-registry/mallard_qr/models.py
=> Fixed bad permissions around workgroups

assets/package-lock.json, python/aristotle-mdr-graphql/aristotle_mdr_graphql/tests/settings.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/tests.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_workgroups.py, python/aristotle-metadata-registry/aristotle_mdr/tests/settings/settings.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py, python/comet-indicator-registry/comet/tests/settings.py, python/comet-indicator-registry/comet/tests/test_comet.py
=> Fixed version comparison 500ing on Indicators where Numerator DSS inclusions are None

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/visibilityInfoBar.html, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
Message now is more accurate and complete.
Sanity checks:
=> Fixed problem with the version warning message in template.

Pipfile.lock
=> Relocks Pipfile

scripts/buildandcopy.sh
=> Make python build quiet

python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Performance enhancements around statuses

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/registrationHistory.html
Sanity checks:
Not it looks like this:
Responsive looks like this:
=> Improved table alignment.

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/header.html, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Fixed Notification Permissions error.

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/mixins.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Fixes Status Reversion page not 403ing if insufficient permissions

assets/package-lock.json, python/aristotle-mdr-graphql/aristotle_mdr_graphql/urls.py, python/aristotle-mdr-graphql/aristotle_mdr_graphql/views.py
=> Fixed 404 in graphql wrapper page when graphql is not enabled.

python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/de_1_initial_search.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/dec_1_initial_search.html
Issues resolved: #1532 
Sanity checks:
=> Changed settings.

assets/package-lock.json, python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/tests.py, python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/views.py, python/aristotle-metadata-registry/aristotle_mdr/managers.py, python/aristotle-metadata-registry/aristotle_mdr/tests/settings/settings.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Added VersionPermission specific checks  to API version views

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/registrationHistory.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/status_history.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_versions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Improved Status Reversion pages, added testing

python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/templates/aristotle_mdr/issues/sublist.html, python/aristotle-metadata-registry/aristotle_mdr/templates/registration/password_change_form.html, python/aristotle-metadata-registry/aristotle_mdr/templates/registration/password_reset_confirm.html, python/aristotle-metadata-registry/aristotle_mdr/templates/registration/password_reset_form.html
=> Password forms improved

python/aristotle-metadata-registry/aristotle_mdr/downloader.py
=> add client specific details in download

python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/views.py
=> Fixes function not being renamed in API

python/aristotle-metadata-registry/aristotle_mdr/forms/bulk_actions.py
Should not pass dynamically generated text to translation function
=> Fix dynamic translations

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/impact.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/review_state_changes.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/widgets/table_checkbox_option.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/widgets/table_checkbox_select.html
Added default title for reviews.
Sanity checks:
=> UI: Improved table render when reviewing status changes. 

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/contentInfoBase.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/dataelementderivation.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/titles/display_title.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/itemLink.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/manageditems/titles/display_title.html
=> Lots of small UI fixes

python/aristotle-glossary/aristotle_glossary/models.py, python/aristotle-metadata-registry/aristotle_mdr/management/commands/glossary_reindex_item.py
=> Commands: Fixes glossary_reindex_item not working when --all used

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/create.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
=> Implemented basic functionality.

python/aristotle-metadata-registry/aristotle_mdr/forms/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/changeStatus.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/changestatus.html
=> UI: Improve status creation and editing layout

python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/helpers/custom_field_icon.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/helpers/field_icon.html
=> Fixed problem with exclamation mark instead of question mark.

python/aristotle-metadata-registry/aristotle_mdr/admin.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/aristotle_mdr/collections/helpers/actionbar.html, python/aristotle-metadata-registry/aristotle_mdr/perms.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/actionbar.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_admin_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py, python/comet-indicator-registry/comet/tests/test_comet.py
=> Added permission check

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_endorse.html
=> Fixed text.

python/aristotle-metadata-registry/aristotle_mdr/perms.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/actionbar.html, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Fixed template error.

python/aristotle-metadata-registry/aristotle_mdr/contrib/autocomplete/templates/aristotle_mdr/actions/autocompleteItem.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/add_link_wizard_0_base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/add_link_wizard_1_select_relation.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/add_link_wizard_2_select_role.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/add_link_wizard_3_select_concepts.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/add_link_wizard_4_confirm.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/edit_link.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/templates/aristotle_mdr_links/actions/helpers/link_end_form.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/tests/test_links.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/autocomplete_light/concept.html, python/aristotle-metadata-registry/aristotle_mdr/templates/autocomplete_light/framework_dimensions.html
Fix for preview windows applies to all multi select boxes
=> Link wizard improvements

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/models.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_accept.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_cancel.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/user/user_request_endorse.html, python/aristotle-metadata-registry/aristotle_mdr/messages.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/actionbar.html
=> Fixed Reviews titles.

python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/tests.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/favourites/templates/aristotle_mdr/favourites/userFavourites.html, python/aristotle-metadata-registry/aristotle_mdr/forms/forms.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/compare/versions.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/comment_form.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/discussion_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/edit.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/edit_comment.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/post.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/workgroup.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/urls/base.py, python/aristotle-metadata-registry/aristotle_mdr/utils/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Sam's UI fixes

assets/src/components/download.vue, python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/tests.py, python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/views.py, python/aristotle-mdr-api/aristotle_mdr_api/v4/tests.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/impact.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/reviewers_review_list.html, python/aristotle-metadata-registry/aristotle_mdr/forms/bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/perms.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/discussions/post.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/download_options.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/registrationHistory.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/status_history.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/search_bar.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_downloads.py, python/aristotle-metadata-registry/aristotle_mdr/utils/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/downloads.py
=> UI improvements

python/aristotle-mdr-graphql/aristotle_mdr_graphql/aristotle_filterset_classes.py, python/aristotle-metadata-registry/aristotle_mdr/managers.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/infobox.html
=> Simplified supersedes queryset permissions

python/aristotle-metadata-registry/aristotle_mdr/contrib/links/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/links/urls.py
=> Linkendforms error fixes

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/actionbar.html
=> Fixed template.

docker/README.md, docker/docker-compose.yml, python/aristotle-mdr-graphql/aristotle_mdr_graphql/templates/aristotle_mdr_graphql/explorer.html, python/aristotle-metadata-registry/aristotle_mdr/models.py
=> GraphQL supersedes fix

assets/src/components/issues/issueModal.vue, python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/templates/aristotle_mdr/issues/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/views/views.py
=> UI: improve display for issues when there are no issue labels

Pipfile.lock, setup.py
=> Bumps: 3.0.6

python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_notifications.py, python/aristotle-metadata-registry/aristotle_mdr/urls/__init__.py, python/aristotle-metadata-registry/aristotle_mdr/urls/base.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
=> Fix notifications not loading

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/registrationHistory.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/status_history.html
=> Adds divider and 'danger' text colour to Status delete link

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/list.html
=> UI: made header extend to full width of UI table

python/aristotle-metadata-registry/aristotle_mdr/required_settings.py
=> Fixes data element wizard link 404ing

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/create.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/create_update_review_form.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/update.html
=> Review Request form is used for create and update templates.

assets/src/components/issues/issueComment.vue, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/changestatus.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py
=> More minor UI fixes

python/aristotle-metadata-registry/aristotle_mdr/constants.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/identifiers/templates/aristotle_mdr/identifiers/identifiers_editor_tab.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/clone_item.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/tests/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
=> Fixes slots and identifiers not displaying in CloneItemView

python/aristotle-metadata-registry/aristotle_mdr/structs.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/titles/display_title.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/breadcrumbs.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/util_tags.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
Reusable breadcrumb object and template tag
=> Breadcrumbs template tag

assets/src/lib/select_all.js, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/select_all.html
=> Added fix for JavaScript error in browse pages.

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/field_help.html
=> Improved modal for help modules.

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/contentInfoBase.html
=> Applied conditional rendering for 'related' tab.

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_1_search.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_wizard_wrapper.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/de_template_wrapper.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/dec_template_wrapper.html, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
=> Wizard breadcrumbs

assets/package-lock.json, assets/src/components/tags/submitTags.vue, assets/src/pages/item_issues.js, assets/src/styles/aristotle.dashboard.less, assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/helpers/tips_section.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/templates/aristotle_mdr/issues/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/templates/aristotle_mdr/issues/sublist.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/base.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/issues.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/update.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/validation.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html
=> Various UI fixes

assets/src/lib/ckeditor_simple_init.js, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/search/searchConceptHelp.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/search/searchHelpPage.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/helpers/paginated_review_list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/stewards/managed_item/list_items.html, python/aristotle-metadata-registry/aristotle_mdr/forms/search.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/concept_history.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/wizard_search_result_item.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/paginated_list.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/user/registration_authority/edit_states.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/workgroup.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/search.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/searchCollection.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/searchDiscussion.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/searchItem.html
=> UI: Better consistency of updated field names across the UI

assets/src/styles/aristotle.dashboard.less
=> Removed highlight color on hover for active nav pill in dashboard

assets/src/styles/aristotle.dashboard.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/helpers/supersedes_display_table.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/issues.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/supersedes_info.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/validation.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py, python/aristotle-metadata-registry/aristotle_mdr/downloader.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_downloads.py, python/aristotle-metadata-registry/aristotle_mdr/views/downloads.py
=> Further UI fixes

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/slots/templates/aristotle_mdr/slots/slots_display.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html
=> Adds borders and shading to differentiate tables on item page

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/helpers/paginated_review_list.html
=> UI: Add due date to review table

setup.py
=> Bump: 3.0.9

assets/test/concept_links_test.js
=> Fixes JS tests failing because of tooltip delay

python/comet-indicator-registry/comet/templates/comet/indicator.html
=> Improved Indicator template page.

assets/package-lock.json, assets/package.json, assets/src/components/issues/issueComment.vue
The library exposes as a Vue plugin by default
=> Import textarea autosize component directly

python/comet-indicator-registry/comet/templates/comet/indicator.html
=> UI: Add reporting information to indicator page

python/aristotle-metadata-registry/aristotle_mdr/templates/search/search.html
=> UI: Improve search help text when it removes filters

python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
=> Forms fixes

setup.py
=> Bump: 3.0.10

python/aristotle-metadata-registry/aristotle_mdr/constants.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/aristotle_help_files/registrationauthority.yaml, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/aristotle_help_files/reversion_formats.yaml, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/aristotle_help_files/versioning_content.yaml, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/compare/versions.html
=> Added help text to button to better explain differences between version formats

setup.py
=> Bump: 3.10.11

python/comet-indicator-registry/comet/models.py
This query needed to be rewritten as the old one was generating some bad
sql where all tables were being left outer joined. This meant the query
was extremely slow when many datasets were present in the registry
=> Improve indicator data sets query

.github/workflows/check-for-unapplied-migrations.yaml, .github/workflows/python.yaml
=> Fix for github actions apt-get not expecting changes

python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/forms/creation_wizards.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/advanced_editor.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/editors.py
Rebased to seperate from download fixes
=> Last updated fix

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/contentInfoBase.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/views/tools.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
=> Fixed issue with related tab. Now it should work as expected.

assets/package-lock.json, assets/src/components/graphs/graphicalRepresentation.vue, python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/views.py
=> Changed graph arrow directions from Indicator to Indicator Set.

python/aristotle-metadata-registry/aristotle_mdr/downloader.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/helpers/statuses.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/util_tags.py
Now the query will be used if not found in cache dictionary
=> Fix supporting items status display in downloads

assets/src/lib/dal_simple_init.js, assets/src/styles/aristotle.autocomplete.css, assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/autocomplete/widgets.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/comet-indicator-registry/comet/models.py
=> Autocomplete fixes

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/concept_editor.html
=> Reference documents heading location.

assets/package-lock.json, assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/concept_help.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/help/views.py
=> Improved look and feel of custom help pages.

setup.py
=> Bumps: 3.0.12

setup.py
=> Bump: 3.0.13

.github/workflows/accessibility.yaml
=> Moved accessibility tests to Github Action

assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/forms.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/clone_item.html, python/comet-indicator-registry/comet/models.py, python/comet-indicator-registry/comet/templates/comet/clone_warning/framework.html, python/comet-indicator-registry/comet/templates/comet/framework.html, python/comet-indicator-registry/comet/templates/comet/helpers/dimension_node.html, python/comet-indicator-registry/comet/templates/comet/helpers/dimension_toc_node.html
=> UI: Improve rendering of framework dimension TOC

python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/impact.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/templates/aristotle_mdr/reviews/review/list.html
=> UI: Update titles for review promotion/demotion

python/aristotle-dataset-extensions/aristotle_dse/models.py, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataSetSpecification.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataset.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/distribution.html, python/comet-indicator-registry/comet/models.py
=> UI: Improve Dataset/Distribution layout

python/aristotle-metadata-registry/aristotle_mdr/templates/search/search.html
=> UI: Minor search layout fixes

python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/concepts/dataset.html, python/aristotle-dataset-extensions/aristotle_dse/templates/aristotle_dse/downloads/html/dataset.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/conceptualdomain.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/dataelementconcept.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/managedContent.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/objectclass.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/property.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/valuedomain.html, python/aristotle-metadata-registry/aristotle_mdr/templates/search/search.html, python/comet-indicator-registry/comet/templates/comet/downloads/html/indicator.html
=> More ui fixes

.github/workflows/accessibility.yaml, assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/generic/views.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/groups/backends.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/templates/stewards/metadata/list.html, python/aristotle-metadata-registry/aristotle_mdr/contrib/stewards/views/manager.py, python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/structs.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/contentInfoBase.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/concepts/titles/display_title.html, python/aristotle-metadata-registry/aristotle_mdr/views/actions.py, python/aristotle-metadata-registry/aristotle_mdr/views/discussions.py, python/aristotle-metadata-registry/aristotle_mdr/views/registrationauthority.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/utils.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py, python/aristotle-metadata-registry/aristotle_mdr/views/wizards.py
=> Breadcrumb improvements

python/aristotle-mdr-api/aristotle_mdr_api/v4/concepts/views.py
…lassed metadata item
Sanity checks:
=> Fixed graph displaying items as _concepts instead of subclass

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/create/de_2_5_make_oc.html
=> Improves back button warning text

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/manageditems/titles/display_title.html, python/comet-indicator-registry/comet/templates/comet/indicator.html
=> UI: Add title to indicator summary table

Pipfile, Pipfile.lock, assets/package-lock.json, python/aristotle-metadata-registry/aristotle_mdr/contrib/serializers/concept_serializer.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/difference_url.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/styled_difference.html, python/aristotle-metadata-registry/aristotle_mdr/templatetags/aristotle_tags.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Added reference document to version comparison

setup.py
=> Bumps: 3.0.14

setup.py
=> Bumps: 3.0.15

python/aristotle-metadata-registry/setup.py, setup.py
=> Release: 3.0.16

assets/src/styles/aristotle.less, python/aristotle-metadata-registry/aristotle_mdr/contrib/slots/templates/aristotle_mdr/slots/slots_display.html
=> Fixed slots extending out of main width

python/aristotle-dataset-extensions/aristotle_dse/tests/test_dse.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/issues/tests.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/tests.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_comparator.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py
=> CHORE: New tests

python/aristotle-metadata-registry/aristotle_mdr/managers.py, python/aristotle-metadata-registry/aristotle_mdr/models.py
=> Fixed use of default mutable arguments 

Pipfile, Pipfile.lock, python/aristotle-mdr-api/aristotle_mdr_api/v3/urls/api.py, python/aristotle-mdr-api/setup.py
=> Updates django-rest-framework and drf-yasg

setup.py
=> Bumps: 3.0.17
