aristotle_mdr/templates/aristotle_mdr/scripts.html, aristotle_mdr/tests/main/test_html_pages.py
Before this can be marked off, its worth:
=> fixed #335

aristotle_mdr/static/aristotle_mdr/aristotle.less
On the search page there is an error in the facet sidebar, this fix removes the padding.
=> Fix for padding on facets

aristotle_easy_installer.py
Fixes up a number of reasonably trivial errors encountered when trying to run the installer under Python 3. The fixes should be more or less version agnostic, and have also been tested for backwards compatibility with Python 2.
=> Python3 fixes

README.rst
:information_desk_person: These changes perform some :nail_care: on the project README.
=> Fixes typos in README

aristotle_mdr/tests/main/test_user_pages.py, aristotle_mdr/views/user_pages.py
Change sandbox queryset to filter for no reviews and no statuses and added a test.
I'm not sure if the filter is correct, as it doesn't correspond to the "published" or "registered" in the issue. Please advise if not correct. Thanks.
=> Fix Issue #500: Modify queryset to filter out unwanted items

.travis.yml, aristotle_mdr/__init__.py, aristotle_mdr/contrib/browse/tests/test_browse.py, aristotle_mdr/contrib/browse/views.py, aristotle_mdr/downloader.py, aristotle_mdr/templates/aristotle_mdr/downloads/pdf/bulk_download.html, aristotle_mdr/templates/aristotle_mdr/downloads/pdf/inline/objectClass.html, aristotle_mdr/templates/aristotle_mdr/downloads/pdf/inline/objectclass.html, aristotle_mdr/templates/aristotle_mdr/downloads/pdf/inline/property.html, aristotle_mdr/tests/main/test_bulk_actions.py, aristotle_mdr/tests/settings/settings.py, aristotle_mdr/tests/settings/templates/search/haystack_elasticsearch.py, aristotle_mdr/tests/settings/templates/search/haystack_whoosh.py, aristotle_mdr/utils/utils.py, aristotle_mdr/views/bulk_actions.py, setup.py
* Improvements to bulk downloads
* Fixed permissions for bulk actions fixes #538
* Improve bulk download customisation, fixes #537
* Removed unnecessary pdf templates
* Increase test coverage
* Add vanilla fail variants for whoosh search engines
* Improved browse faceting fixes #533 (#534)
* pep
* fixes #537
* pep
* add haystack elasticsearch, because the new version has broken stuff
* change haystack requirement
* fix haystack import
* fix haystack import
* remove debug print
* test tweaks
=> v.1.4.2 Improvements to bulk downloads

aristotle_mdr/contrib/slots/templates/aristotle_mdr/slots/pdf/slots_display.html, aristotle_mdr/downloader.py, aristotle_mdr/templates/search/indexes/aristotle_mdr/managedobject_text.txt
Modified slot_display template to use new Slot models introduced on v1.5
Added request to downloaded context to be able to render the counter of similar slots.
Fixed index generation to include the slot name using new Slot Models.
This is a continuation of PR: #634
=> Fixed Slot usage in pdf template and index to work with new Slot models

aristotle_mdr/templates/aristotle_mdr/actions/advanced_editor.html
**Problem:**
when loading the advanced editor, on a bootstrap modal, two plugins were not initialized: autocomplete-light, ckeditor
**Fixes:**
Loading the autocomplete.init.js with JQuery, on modal display, to initialize the autocomplete-light plugin.
Triggering DOMContentLoaded event to initialize the ckeditor when the bootstrap modal is loaded.
**Autocomplete-light problem**
select2 plugin not loaded on advanced editor (screenshot taken from registry.aristotlemetadata.com):
**ckeditor problem**
ckeditor is not loading on my environments (`Django 1.8`, `ckeditor 5.3.0`, latest Aristotle) is not loading on bootstrap modal. But I noticed that is working on registry.aristotlemetadata.com not sure which versions are used on that site.
=> Added JS fixes, on advanced editor when using bootstrap modals

aristotle_mdr/static/autocomplete_light/select2.js, aristotle_mdr/templates/aristotle_mdr/concepts/dataElement.html
* Added missing bootstrap modal on dataElement template to enable `Edit/Add` links
* Initialization fixes for latest django-autocomplete-light plugin. In version `3.2.10` a conditional was added on the initialization: https://github.com/yourlabs/django-autocomplete-light/commit/74627c5d771b10eaa2c55f95406379b0cf047aba
=> Fixes for autocomplete light plugin and bootstrap modals

aristotle_mdr/templates/search/searchItem.html
Some characters were escaped on the search results:
To avoid this we can follow the same as idea as in [concept_list_details.html](https://github.com/aristotle-mdr/aristotle-metadata-registry/blob/e1b88f24b0c6934b65e99425c3e462710b3a8a5b/aristotle_mdr/templates/aristotle_mdr/helpers/concept_list_details.html#L2) by first `striptags`, then `safe` and finally `truncatewords`
=> Better description display for searchItem on Search results

python/aristotle-metadata-registry/aristotle_mdr/forms/fields.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/helpers/changestatus.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/widgets/table_checkbox_option.html, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/widgets/table_checkbox_select.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py, python/aristotle-metadata-registry/aristotle_mdr/widgets/widgets.py
=> Automatic deselections on change status

python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py
This fixes a Request error exception for the "Notify new people" checkbox.
=> Fixed request error for unchecked 'notify new people' checkbox.

python/aristotle-bg-workers/aristotle_bg_workers/tasks.py, python/aristotle-bg-workers/aristotle_bg_workers/utils.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/async_signals/utils.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/tests.py, python/aristotle-metadata-registry/aristotle_mdr/contrib/reviews/views.py, python/aristotle-metadata-registry/aristotle_mdr/required_settings.py, python/aristotle-metadata-registry/aristotle_mdr/signals.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_bulk_actions.py, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_html_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/user_pages.py, python/aristotle-metadata-registry/aristotle_mdr/views/views.py
This makes sure celery tasks start after the current database
transaction is complete so that item lookups can be done. The will need
to be done if future for any celery tasks run during a transaction
Util functions have been added to help with this
=> Change how celery tasks in transactions are run

python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/actions/compare/compare_items.html, python/aristotle-metadata-registry/aristotle_mdr/tests/main/test_comparator.py, python/aristotle-metadata-registry/aristotle_mdr/views/comparator.py, python/aristotle-metadata-registry/aristotle_mdr/views/versions.py
=> Fixed failure when URL query string is empty in comparator

python/aristotle-metadata-registry/aristotle_mdr/models.py, python/aristotle-metadata-registry/aristotle_mdr/views/tools.py
=> Fix for indicator, relation item pages 500ing when /related/ accessed

python/comet-indicator-registry/comet/templates/comet/static/about_comet_mdr.html, python/comet-indicator-registry/comet/templates/comet/static/framework.html, python/comet-indicator-registry/comet/templates/comet/static/qualitystatement.html
=> Fixed comet help page 500ing when template doesn't exist

mypy.ini, setup.cfg
Pulling into 3.1.0 feature branch, since this impacts #1554
=> Ignore migrations directories for python linting

python/aristotle-metadata-registry/aristotle_mdr/views/downloads.py
This was removed as it was coming through sentry and probably was meant
for debugging only
=> Remove critical log for celery result

python/aristotle-metadata-registry/aristotle_mdr/contrib/aristotle_pdf/downloader.py, python/aristotle-metadata-registry/aristotle_mdr/templates/aristotle_mdr/downloads/html/cover_footer.html
Downloads without a cover page and table of contents had incorrect page
numbering due to numbering changes required to deal with those leading
pages
=> Fix page numbering for small downloads

python/aristotle-metadata-registry/aristotle_mdr/contrib/help/templates/aristotle_mdr_help/helpers/tips_section.html
These links are accessible from the wizards where we don't want users to
navigate to a new page directly
=> Make help page links open in new tab

python/aristotle-metadata-registry/aristotle_mdr/contrib/custom_fields/forms.py
=> Fixed custom field enum values incorrectly displaying as 'old' even if they weren't

python/aristotle-metadata-registry/aristotle_mdr/contrib/browse/templates/aristotle_mdr_browse/apps_list.html
=> Fixed breadcrumbs spacing being unnecessarily wide on metadata browse

assets/src/styles/aristotle.less
Flex shrink is on by default. This was causing issues when the navbar
stacked
=> Make the navbar able to shrink within flexbox
